### ISSUE TITLE
XGBClassifier.DumpModelEx throws EntryPointNotFoundException

### ISSUE THREAD

**Issue by suoranta** [PicNet/XGBoost.Net#10]
XGBClassifier.DumpModelEx throws EntryPointNotFoundException because entry point XGBoosterDumpModelEx is not found in libxgboost.dll. I inspected the DLL in question and I believe that the entry point was perhaps meant to be XGBoosterDumpModel.

**Comment by cycloidistic** [comment]
Yep, I think you're right. I'm fixing that now and hopefully will be able to update the nuget package soon.

Just to clarify how this happened, what did the code which caused this error look like? It would help in testing.

**Comment by suoranta** [comment]
Thanks, I simply instantiated an XGBClassifier, fitted and called DumpModelEx:
```
XGBClassifier classifier = new XGBClassifier();
classifier.Fit(X,Y);
var dump = classifier.DumpModelEx();
```

**Comment by cycloidistic** [comment]
Thanks for that.

It should be fixed now. The fix is also part of the latest nuget package release.
