### ISSUE TITLE
Issue with nuget package 

### ISSUE THREAD

**Issue by mdabros** [PicNet/XGBoost.Net#24]
Hi @gatapia ,

I am having an issue with the nuget package when used as a dependency for another package. It seems that nuget tries to add the native dll as a reference for the targeted project:

![image](https://user-images.githubusercontent.com/9001637/40295511-d373857c-5cd9-11e8-88da-7605e0dd7e86.png)

To avoid nuget trying to do this, you can add the following to your .nuspec file:

```csharp
<references>
   <reference file="XGBoost.dll" />
</references>
```

This will tell nuget that the XBoost.dll is the only dll to reference during install. 
I tried this locally by modifying the PicNet.XGBoost.Net package, and it solves the issue. 

Could you release a new version of the nuget package with this added to the .nuspec file? It would help me a lot since currently my own package doesn't work because of this issue.

best regards
Mads

**Comment by gatapia** [comment]
Hi Mads,

I've updated the NuGet package and it installs, have not tested the
functionality though.  Will update the test project later today.

Cheers,

Guido

**Comment by mdabros** [comment]
Hi Guido, 

Thanks for responding to quickly! I have tested the new package and everything seems to work now. 
Thanks for your help!

best regards
Mads

**Comment by pranavmehta** [comment]
@gatapia I still have have the exact same issue even though this has been marked as closed. Any tips to get it working would be helpful. Version 0.2.1 does not have this issue. Thanks.
