### ISSUE TITLE
Is this still active?

### ISSUE THREAD

**Issue by mdabros** [PicNet/XGBoost.Net#30]
Hi @gatapia and @PicNet  

Is this repository still active? I routinely get requests about features and/or new versions of xgboost.net via my SharpLearning wrapper for this library. So there still seems to be a need for it :).

**Comment by gatapia** [comment]
Sorry, no I have not mantained this for many years now.  I will put a notice in the readme.

**Comment by mdabros** [comment]
OK, sad to hear, and sounds good if you put a notice in the readme. 
I might copy this to a new repo, and try to get it up to date. But only if this is OK by you @gatapia?

**Comment by gatapia** [comment]
Of course, go for it

**Comment by mdabros** [comment]
@gatapia FYI: I have renewed the code here: https://github.com/mdabros/XGBoostSharp with an initial release adding a few additional features, and will continue to add features from there. Thanks for the initiating this project, and for letting it continue in a new repo :thumbsup:.

**Comment by gatapia** [comment]
> @gatapia FYI: I have renewed the code here: https://github.com/mdabros/XGBoostSharp with an initial release adding a few additional features, and will continue to add features from there. Thanks for the initiating this project, and for letting it continue in a new repo 👍.

Thats awesome. I put a note on the readme.

**Comment by mdabros** [comment]
@gatapia Thanks for adding the note! 👍
