### ISSUE TITLE
Failed to train if decimal separator in regional settings is ',' (comma)

### ISSUE THREAD

**Issue by slonoten** [PicNet/XGBoost.Net#7]
XGBGetLastError returns:

> Invalid Parameter format for base_score expect float but value='0,5'

Possible solution is to use `System.Globalization.NumberFormatInfo` to specify dot as decimal separator:

```
    public void SetParameters(IDictionary<string, Object> parameters)
    {
      var nfi = new NumberFormatInfo { NumberDecimalSeparator = "." };

      SetParameter("max_depth", ((int)parameters["max_depth"]).ToString());
      SetParameter("learning_rate", ((float)parameters["learning_rate"]).ToString(nfi));
        ....
    }
```

**Comment by cycloidistic** [comment]
Thanks for the possible solution.

When did you get this error? Was it after doing `new XGBRegressor()/new XGBClassifier()`, after doing `Fit()`, or after doing `Predict()`?

 Also, would you be able to share what code you used to create this error?

**Comment by slonoten** [comment]
I got this error after doing Fit().

Simplest way to reproduce this issue is temporary change decimal separator character in control panel regional settings from '.' (dot) to ',' (comma). Another way is add 

> Thread.CurrentThread.CurrentCulture = CultureInfo.CreateSpecificCulture("ru-RU"); 

to code of unit test 'Predict' before call 

> XGBRegressor xgbr = new XGBRegressor();

If you add this code before 

> float[][] dataTrain = GetDataTrain();

you'll get similar error in float.Parse(string) call, which can be cured if specify instance of NumberFormatInfo as second parameter.

**Comment by cycloidistic** [comment]
Ok, I've replicated the problem and I've pushed the [changes](https://github.com/PicNet/XGBoost.Net/commit/780ab603bbb8d5e0890a63382bd0fb55121e3848). 

If you want, I can update the NuGet package tomorrow with the change.
